spring.datasource.url=jdbc:mysql://100.111.90.29:3307/a0722849_maxsim?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=a0722849_maxsim
spring.datasource.password=R870nt55@

upload.directory=./uploads-local
spring.thymeleaf.cache=false
spring.web.resources.cache.cachecontrol.max-age=0
logging.level.ru.tattoo.maxsim=DEBUG
server.port=8081