# ?????? spring.profiles=prod ???????????:
spring.config.activate.on-profile=prod

# ???? ??? ???????? ? Docker ??????????
upload.directory=/app/img/images

# ??????????? ???????????
logging.level.ru.tattoo.maxsim=WARN
logging.level.org.springframework.web=WARN

# ???????? ??????????? ??? ??????????????????
spring.thymeleaf.cache=true
spring.web.resources.cache.cachecontrol.max-age=86400

# ???????? ?????? ??????
server.error.include-stacktrace=never
server.error.include-message=never